version: '3'
services:
  postgredb:
    image: postgres
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-postgres}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-satya}
      POSTGRES_USER: ${KONG_PG_USER:-satya}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-satya}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - my-data:/var/lib/postgresql/data/ 
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - my-data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/konga --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
  elastic-node-01:
    image: elasticsearch:7.10.1
    container_name: elastic-node-01
    environment:
      - node.name=elastic-node-01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-node-02
      - cluster.initial_master_nodes=elastic-node-01,elastic-node-02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.docker/elastic/node-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  elastic-node-02:
    image: elasticsearch:7.10.1
    container_name: elastic-node-02
    environment:
      - node.name=elastic-node-02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-node-01
      - cluster.initial_master_nodes=elastic-node-01,elastic-node-02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.docker/elastic/node-02:/usr/share/elasticsearch/data
    networks:
      - elastic
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./.docker/zookeeper/data:/data
      - ./.docker/zookeeper/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./.docker/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
networks:
  elastic:
    driver: bridge
volumes:
  my-data: 